module.exports = {
  darkMode: 'selector',
  content: ['./src/**/*.{html,ts}', './projects/**/*.{html,ts}'],
  theme: {
    fontSize: {
      'xs': ['12px', { lineHeight: '16px' }],
      'sm': ['13px', { lineHeight: '16px' }],
      'base-1': ['14px', { lineHeight: '16px' }],
      'base-2': ['14px', { lineHeight: '16.8px' }],
      'base-3': ['14px', { lineHeight: '20px' }],
      'base-4': ['14px', { lineHeight: '24px' }],
      'md': ['16px', { lineHeight: '24px' }],
      'lg': ['20px', { lineHeight: '24px' }],
      'xl': ['24px', { lineHeight: '32px' }],
      '2xl': ['32px', { lineHeight: '40px' }]
    },
    spacing: {
      0: '0',
      'xs': '4px',
      'sm': '8px',
      'md': '12px',
      'lg': '16px',
      'xl': '24px',
      6: '24px',
      7: '28px',
      8: '32px',
      10: '40px',
      16: '64px',
      56: '224px',
      72: '288px'
    },
    extend: {
      colors: {
        'background': '#fffefc',
        'black-0': '#000000',
        'black-1': '#19264d',
        'blue-2': '#173fc4',
        'blue-4': '#2054ff',
        'blue-5': '#3363ff',
        'blue-6': '#86a3f9',
        'box-shadow': '#00000012',
        'gray-0': '#697496',
        'green': '#29ab7f',
        'green-2': '#0BCB8B',
        'green-dark': '#0a8d61',
        'green-light': '#c8f9e9',
        'menu-hover': '#e3e9ff',
        'menu-selected': '#d3dcfb',
        'neutral-1': '#090d1b',
        'neutral-2': '#19264d',
        'neutral-3': '#3d455c',
        'neutral-4': '#49536e',
        'neutral-6': '#8f9bbc',
        'neutral-7': '#d8ddeb',
        'neutral-8': '#cad2e5',
        'neutral-9': '#e8edfa',
        'neutral-11': '#f0f1f5',
        'neutral-12': '#f5f6fa',
        'neutral-13': '#0e1215',
        'neutral-14': '#8fa7bc',
        'neutral-15': '#cbcaca3d',
        'red': '#df3a3a',
        'red-2': '#e16251',
        'red-3': '#DF3A3A',
        'red-4': '#d92626',
        'red-dark': '#a92323',
        'red-light': '#fcdfdf',
        'red-light-2': '#ebb1b1',
        'white': '#fff',
        'yellow': '#e5b00e',
        'yellow-dark': '#a37a00',
        'yellow-light': '#fec',
        'yellow-light-2': '#ecd19d',
        'yellow-1': '#fafaf9',
        'yellow-2': '#f5b73d'
      }
    },
    backgroundImage: {
      none: 'none',
      'search-icon': "url('assets/icons/search.svg')",
      'check-box': "url('assets/icons/checkbox.svg')",
      'checkbox-unchecked': "url('assets/icons/checkbox-unchecked.svg')",
      'dropdown-icon': "url('assets/icons/dropdown-arrow.svg')",
      'linear-gradient-neutral': "linear-gradient(to right, #F5F6FA, #F0F1F5)",
      'dotted': "radial-gradient(#c9cdd8 1px, transparent 1px)"
    },
    boxShadow: {
      'tableCol1': '0px -10px 50px 0px rgba(0, 0, 0, 0.03), 0px 20px 50px 0px rgba(0, 0, 0, 0.04)',
    }
  },
  plugins: [],
 };
